name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: Test
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://orgb93b78fb.crm.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: https://orgd59a7a39.crm.dynamics.com
      CLIENT_ID: 23b6bbfa-11b7-41f3-bd84-9c59ef6b5c82
      TENANT_ID: 84f1a83f-7c4c-413f-bca0-92367bc23980      
    secrets:
      envSecret: ${{ secrets.PowerPlatformDEV }}
